excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://3laa-Khalil-Alarabi.github.io
title: 3laa Khalil Alarabi
email: 
author: 3laa Khalil Alarabi
description: My awesome new site
paginate: 3
google_analytics: 